# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2e3cef595cdc1436eb508703ec482c6d"
name = "quickship-delivery"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_delivery_customizations,read_products,write_delivery_customizations"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
